name: Spanish README Maintenance

on:
  push:
    branches: [main, master]
    paths:
      - 'README.md'
  pull_request:
    branches: [main, master]
    paths:
      - 'README.md'

jobs:
  check-spanish-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if README.md changed
        id: readme-changed
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "README.md"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Check if Spanish README exists
        id: spanish-exists
        run: |
          if [ -f "README-es.md" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Get README.md last modified date
        id: readme-date
        run: |
          README_DATE=$(git log -1 --format="%ct" -- README.md)
          echo "readme_date=$README_DATE" >> $GITHUB_OUTPUT

      - name: Get Spanish README last modified date
        id: spanish-date
        if: steps.spanish-exists.outputs.exists == 'true'
        run: |
          SPANISH_DATE=$(git log -1 --format="%ct" -- README-es.md)
          echo "spanish_date=$SPANISH_DATE" >> $GITHUB_OUTPUT

      - name: Check if Spanish README needs update
        id: needs-update
        run: |
          if [ "${{ steps.spanish-exists.outputs.exists }}" == "false" ]; then
            echo "needs_update=true" >> $GITHUB_OUTPUT
            echo "reason=missing" >> $GITHUB_OUTPUT
          elif [ "${{ steps.readme-changed.outputs.changed }}" == "true" ]; then
            README_DATE=${{ steps.readme-date.outputs.readme_date }}
            SPANISH_DATE=${{ steps.spanish-date.outputs.spanish_date }}
            if [ "$README_DATE" -gt "$SPANISH_DATE" ]; then
              echo "needs_update=true" >> $GITHUB_OUTPUT
              echo "reason=outdated" >> $GITHUB_OUTPUT
            else
              echo "needs_update=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "needs_update=false" >> $GITHUB_OUTPUT
          fi

      - name: Create issue for Spanish README update
        if: steps.needs-update.outputs.needs_update == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: 'spanish-translation',
              state: 'open'
            });

            // Don't create duplicate issues
            if (issues.length > 0) {
              console.log('Spanish translation issue already exists');
              return;
            }

            const reason = '${{ steps.needs-update.outputs.reason }}';
            const title = reason === 'missing' 
              ? '📝 Spanish README Translation Needed (README-es.md)' 
              : '🔄 Spanish README Translation Update Required (README-es.md)';
            
            const body = reason === 'missing'
              ? `## Spanish README Missing\n\nThe main README.md exists but there is no Spanish translation (README-es.md).\n\n### Action Required\n- [ ] Create README-es.md with Spanish translation of the current README.md\n- [ ] Follow the translation guidelines in our documentation\n- [ ] Ensure all links and technical terms are properly translated\n\n### Translation Guidelines\n- Translate all sections while maintaining the original structure\n- Keep code blocks and commands unchanged\n- Translate user-facing text and descriptions\n- Maintain markdown formatting\n- Keep technical terms in English when appropriate (e.g., API, GitHub, etc.)\n\n### Resources\n- [README.md](./README.md) - Source file to translate\n- [Translation Guidelines](./.github/TRANSLATION_GUIDELINES.md) - Detailed guidelines\n\n**Auto-generated by Spanish README Maintenance workflow**`
              : `## Spanish README Update Required\n\nThe main README.md has been updated and the Spanish translation (README-es.md) needs to be updated accordingly.\n\n### Changes Detected\nRecent changes were detected in README.md that need to be reflected in the Spanish version.\n\n### Action Required\n- [ ] Review changes in README.md\n- [ ] Update README-es.md with corresponding Spanish translations\n- [ ] Ensure consistency between both versions\n\n### Translation Guidelines\n- Compare the current README.md with README-es.md\n- Translate new or modified sections\n- Maintain the same structure and formatting\n- Keep technical terms consistent\n\n### Resources\n- [README.md](./README.md) - Updated source file\n- [README-es.md](./README-es.md) - Spanish version to update\n- [Translation Guidelines](./.github/TRANSLATION_GUIDELINES.md) - Detailed guidelines\n\n**Auto-generated by Spanish README Maintenance workflow**`;

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['spanish-translation', 'documentation', 'help-wanted']
            });

      - name: Add comment to PR if needed
        if: github.event_name == 'pull_request' && steps.needs-update.outputs.needs_update == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const reason = '${{ steps.needs-update.outputs.reason }}';
            const message = reason === 'missing'
              ? '📝 **Spanish Translation Needed**: This PR modifies README.md but no Spanish translation (README-es.md) exists. Please consider adding a Spanish version or an issue will be created to track this.'
              : '🔄 **Spanish Translation Update**: This PR modifies README.md. The Spanish translation (README-es.md) will need to be updated accordingly. An issue will be created to track this translation update.';

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });